Gemfile:
  optional:
    ':development':
      - gem: 'puppet-lint-param-docs'
      - gem: 'puppet-lint-variable_contains_upcase'
      - gem: 'puppet-lint-trailing_newline-check'

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
  minimum_code_coverage_percentage: 95
